// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dukfxfkueuldeaogfgad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1a2Z4Zmt1ZXVsZGVhb2dmZ2FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MDg0MzIsImV4cCI6MjA2MTE4NDQzMn0.sm6QZwZ_ZJ4Xizviwvb6j06U-BKqJJSlWVVRB8NIoMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);